# World Happiness Report

## Import Libraries

In [1]:
import pandas as pd
import numpy as np

## Load Data

In [3]:
df = pd.read_csv(r"C:\Users\twins\OneDrive\Desktop\Data\project\world-happiness-report\archive\2019.csv")

##  Basic Overview

In [76]:
df.shape

(156, 9)

In [6]:
df.info

<bound method DataFrame.info of      Overall rank         Country or region  Score  GDP per capita  \
0               1                   Finland  7.769           1.340
1               2                   Denmark  7.600           1.383
2               3                    Norway  7.554           1.488
3               4                   Iceland  7.494           1.380
4               5               Netherlands  7.488           1.396
..            ...                       ...    ...             ...
151           152                    Rwanda  3.334           0.359
152           153                  Tanzania  3.231           0.476
153           154               Afghanistan  3.203           0.350
154           155  Central African Republic  3.083           0.026
155           156               South Sudan  2.853           0.306

     Social support  Healthy life expectancy  Freedom to make life choices  \
0             1.587                    0.986                         0.596
1             1.573                    0.996                         0.592
2             1.582                    1.028                         0.603
3             1.624                    1.026                         0.591
4             1.522                    0.999                         0.557
..              ...                      ...                           ...
151           0.711                    0.614                         0.555
152           0.885                    0.499                         0.417
153           0.517                    0.361                         0.000
154           0.000                    0.105                         0.225
155           0.575                    0.295                         0.010

     Generosity  Perceptions of corruption
0         0.153                      0.393
1         0.252                      0.410
2         0.271                      0.341
3         0.354                      0.118
4         0.322                      0.298
..          ...                        ...
151       0.217                      0.411
152       0.276                      0.147
153       0.158                      0.025
154       0.235                      0.035
155       0.202                      0.091

[156 rows x 9 columns]>

In [7]:
df.describe()

,Overall rank,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,78.500000,5.407096,0.905147,1.208814,0.725244,0.392571,0.184846,0.110603
std,45.177428,1.113120,0.398389,0.299191,0.242124,0.143289,0.095254,0.094538
min,1.000000,2.853000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,39.750000,4.544500,0.602750,1.055750,0.547750,0.308000,0.108750,0.047000
50%,78.500000,5.379500,0.960000,1.271500,0.789000,0.417000,0.177500,0.085500
75%,117.250000,6.184500,1.232500,1.452500,0.881750,0.507250,0.248250,0.141250
max,156.000000,7.769000,1.684000,1.624000,1.141000,0.631000,0.566000,0.453000

## Missing Values

In [9]:
# checking foe null values
df.isnull().sum()

Overall rank                    0
Country or region               0
Score                           0
GDP per capita                  0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       0
dtype: int64

In [38]:
# checking  for columns
df.columns

Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

## Correlation Analysis

In [19]:
# Top 10 happiest countries

df.nlargest(10,'Score')[['Country or region','Score']]

  Country or region  Score
0           Finland  7.769
1           Denmark  7.600
2            Norway  7.554
3           Iceland  7.494
4       Netherlands  7.488
5       Switzerland  7.480
6            Sweden  7.343
7       New Zealand  7.307
8            Canada  7.278
9           Austria  7.246

In [25]:
# Top 10 happiest countries

df.nsmallest(10, 'Score')[['Country or region', 'Score']]

            Country or region  Score
155               South Sudan  2.853
154  Central African Republic  3.083
153               Afghanistan  3.203
152                  Tanzania  3.231
151                    Rwanda  3.334
150                     Yemen  3.380
149                    Malawi  3.410
148                     Syria  3.462
147                  Botswana  3.488
146                     Haiti  3.597

In [39]:
# See Finland's scores on every factor

df[df['Country or region']=='Finland']

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.34,1.587,0.986,0.596,0.153,0.393

In [36]:
# Bottom country

df[df['Overall rank']==156]

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
155,156,South Sudan,2.853,0.306,0.575,0.295,0.01,0.202,0.091

In [44]:
# How much does each factor correlate with happiness?

df.corr(numeric_only=True)['Score'].sort_values(ascending=False).round(2)

Score                           1.00
GDP per capita                  0.79
Healthy life expectancy         0.78
Social support                  0.78
Freedom to make life choices    0.57
Perceptions of corruption       0.39
Generosity                      0.08
Overall rank                   -0.99
Name: Score, dtype: float64

This means money alone doesn't make you happy — you also need health and people who care about you.

In [55]:
# Countries with high GDP but below average happiness

avg_happiness = df['Score'].mean()
avg_wealthy= df['GDP per capita'].mean()

wealthy_unhappy = df[
                    (df['GDP per capita'] > avg_wealthy) &
                    (df['Score'] < avg_happiness)
                    ][['Country or region', 'Score', 'GDP per capita', 'Social support']].sort_values('Score',ascending=  False)

print(wealthy_unhappy)

          Country or region  Score  GDP per capita  Social support
77   Bosnia and Herzegovina  5.386           0.945           1.212
78                   Turkey  5.373           1.183           1.360
79                 Malaysia  5.339           1.221           1.171
80                  Belarus  5.323           1.067           1.465
81                   Greece  5.287           1.181           1.156
82                 Mongolia  5.285           0.948           1.531
83          North Macedonia  5.274           0.983           1.294
86             Turkmenistan  5.247           1.052           1.538
87                  Algeria  5.211           1.002           1.160
89               Azerbaijan  5.208           1.043           1.147
90                  Lebanon  5.197           0.987           1.224
91                Indonesia  5.192           0.931           1.203
92                    China  5.191           1.029           1.125
96                 Bulgaria  5.011           1.092           1.513
103                   Gabon  4.799           1.057           1.183
105            South Africa  4.722           0.960           1.351
106                 Albania  4.719           0.947           0.848
107               Venezuela  4.707           0.960           1.427
116                    Iran  4.548           1.100           0.842
123                 Tunisia  4.461           0.921           1.000
125                    Iraq  4.437           1.043           0.980
129               Sri Lanka  4.366           0.949           1.265
136                   Egypt  4.166           0.913           1.039
147                Botswana  3.488           1.041           1.145

Middle East & North African countries have high GDP because of its high resource and geography.but governance issues, inequality, and political instability drag happiness down.

In [57]:
# Countries with low GDP but above average happiness

poor_happy = df[
                (df['GDP per capita'] < avg_wealthy) &
                (df['Score']>avg_happiness)
                 ][['Country or region', 'Score', 'GDP per capita', 'Social support']].sort_values('Score',ascending=  False)

print(poor_happy )

   Country or region  Score  GDP per capita  Social support
26         Guatemala  6.436           0.800           1.269
34       El Salvador  6.253           0.794           1.242
40        Uzbekistan  6.174           0.745           1.529
44         Nicaragua  6.105           0.694           1.325
45            Kosovo  6.100           0.882           1.232
55           Jamaica  5.890           0.831           1.478
58          Honduras  5.860           0.642           1.236
60           Bolivia  5.779           0.776           1.209
62          Paraguay  5.743           0.855           1.475
66          Pakistan  5.653           0.677           0.886
68       Philippines  5.631           0.807           1.293
70           Moldova  5.529           0.685           1.328
73        Tajikistan  5.467           0.493           1.098

LATIN American countries shows consistently score high on happiness despite lower wealth. Their Social support scores — consistently above 1.2. Strong families, tight communities, rich culture. People show up for each other.

In [61]:
# Compare average social support — Latin America vs wealthy unhappy countries

latin = ['Guatemala', 'El Salvador', 'Nicaragua', 'Honduras', 'Bolivia', 'Jamaica']
rich_unhappy_countries = ['Greece', 'Turkey', 'Malaysia', 'Belarus']

print("Latin America avg social support:")
print(df[df['Country or region'].isin(latin)]['Social support'].mean().round(3))

print("\nRich unhappy countries avg social support:")
print(df[df['Country or region'].isin(rich_unhappy_countries)]['Social support'].mean().round(3))

Latin America avg social support:
1.293

Rich unhappy countries avg social support:
1.288

In [67]:
# Countries with high health expectancy but above average happiness

avg_happiness = df['Score'].mean()
avg_healthy= df['Healthy life expectancy'].mean()

healthy_unhappy = df[
                    (df['Healthy life expectancy'] > avg_healthy) &
                    (df['Score'] < avg_happiness)
                    ][['Country or region', 'Score', 'Healthy life expectancy', 'Perceptions of corruption','Freedom to make life choices']].sort_values('Score',ascending=  False)

print(healthy_unhappy)

          Country or region  Score  Healthy life expectancy  \
77   Bosnia and Herzegovina  5.386                    0.845
78                   Turkey  5.373                    0.808
79                 Malaysia  5.339                    0.828
80                  Belarus  5.323                    0.789
81                   Greece  5.287                    0.999
83          North Macedonia  5.274                    0.838
87                  Algeria  5.211                    0.785
88                  Morocco  5.208                    0.782
89               Azerbaijan  5.208                    0.769
90                  Lebanon  5.197                    0.815
92                    China  5.191                    0.893
93                  Vietnam  5.175                    0.851
96                 Bulgaria  5.011                    0.815
100                  Jordan  4.906                    0.815
106                 Albania  4.719                    0.874
107               Venezuela  4.707                    0.805
115                 Armenia  4.559                    0.815
116                    Iran  4.548                    0.785
118                 Georgia  4.519                    0.752
123                 Tunisia  4.461                    0.815
129               Sri Lanka  4.366                    0.831
132                 Ukraine  4.332                    0.739

     Perceptions of corruption  Freedom to make life choices
77                       0.006                         0.212
78                       0.106                         0.195
79                       0.024                         0.508
80                       0.142                         0.235
81                       0.034                         0.067
83                       0.034                         0.345
87                       0.114                         0.086
88                       0.076                         0.418
89                       0.182                         0.351
90                       0.027                         0.216
92                       0.100                         0.521
93                       0.073                         0.543
96                       0.004                         0.311
100                      0.130                         0.383
106                      0.027                         0.383
107                      0.047                         0.154
115                      0.064                         0.283
116                      0.125                         0.305
118                      0.164                         0.346
123                      0.055                         0.167
129                      0.047                         0.470
132                      0.010                         0.178

Eastern European countries have good healthcare systems , but low happiness due to corruption and low freedom scores. Also,some Asian countries — long life expectancy culturally, but less personal freedom.

In [71]:
# Countries with low health expectancy but above average happiness

avg_happiness = df['Score'].mean()
avg_healthy= df['Healthy life expectancy'].mean()

low_healthy_happy = df[
                    (df['Healthy life expectancy'] < avg_healthy) &
                    (df['Score'] > avg_happiness)
                    ][['Country or region', 'Score', 'Healthy life expectancy', 'Perceptions of corruption','Freedom to make life choices','Social support']].sort_values('Score',ascending=  False)

print(low_healthy_happy)

    Country or region  Score  Healthy life expectancy  \
38  Trinidad & Tobago  6.192                    0.713
60            Bolivia  5.779                    0.706
66           Pakistan  5.653                    0.535
68        Philippines  5.631                    0.657
71              Libya  5.525                    0.673
73         Tajikistan  5.467                    0.718

    Perceptions of corruption  Freedom to make life choices  Social support
38                      0.016                         0.489           1.477
60                      0.064                         0.511           1.209
66                      0.098                         0.313           0.886
68                      0.107                         0.558           1.293
71                      0.152                         0.416           1.303
73                      0.144                         0.389           1.098

In [70]:
df[df['Country or region'].isin(['Trinidad & Tobago', 'Bolivia', 'Pakistan'])]

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
38,39,Trinidad & Tobago,6.192,1.231,1.477,0.713,0.489,0.185,0.016
60,61,Bolivia,5.779,0.776,1.209,0.706,0.511,0.137,0.064
66,67,Pakistan,5.653,0.677,0.886,0.535,0.313,0.220,0.098

Pakistan has the worst health score in this list and the lowest freedom score — yet still above average happiness. Strong religious faith and tight family structures. Pakistani culture has extremely deep family bonds — people rarely face hardship alone.

Trinidad & Tobago has the highest happiness in this group despite poor health. But look at that corruption score — 0.016 — almost zero perceived corruption. People trust their government and each other. That trust alone boosts happiness significantly.

## Conclusion

- GDP correlates 0.79 - Wealth matters most numerically
- Greece, Turkey unhappy despite wealth - Money without freedom/community fails
- Guatemala, Nicaragua happy despite poverty - Community beats wealth
- Pakistan, Philippines happy despite poor health - Culture and faith fill the gap

Happiness isn't one thing ,it's a combination of wealth, health, freedom AND community. No single factor guarantees it

In [75]:
# Drop duplicates if any
df = df.drop_duplicates()

# Fill missing numbers with column median (safer than mean — remember outliers!)
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

# Reset index after cleaning
df = df.reset_index(drop=True)

print(f"Clean dataset shape: {df.shape}")
print(df.isnull().sum())

Clean dataset shape: (156, 9)
Overall rank                    0
Country or region               0
Score                           0
GDP per capita                  0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       0
dtype: int64

In [74]:
df.to_csv('happiness_clean.csv', index=False)
print("Saved!")

Saved!